### ISSUE TITLE
Cauldron Bottling Wonkiness

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#261]
### Expected Behavior
I had a brew ready to go in a cauldron, and I tested emptying it out fully three different times. Once was with normal phials, another was with splash phials and then I did it with lingering phials. I will mention that I used an Everful Urn to fill the cauldron up each time.

### Actual Behavior
The strange thing I noticed was that emptying the cauldron with splash and linger bottles gave me two brews and emptied the cauldron fully, while emptying it with normal phials gave me three brews and left an unusable dribble at the bottom of the cauldron, which I couldn't empty without replacing the cauldron.

### Steps to Reproduce
1. Setup a cauldron ready to make potions (heated, powered etc.)
2. Make a brew of any kind. I used invisibility brews for my more thorough testing.
3. Empty it using splash or lingering phials. You should get two brews and empty the cauldron fully.
4. Repeat step 1 and 2, and then empty the cauldron with normal phials. You should get three brews and leave the previously mentioned unusable dribble of brew at the bottom of the cauldron.

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
MC: 1.12.2
BW: 0.0.19.26
Forge: 14.23.5.2815
Patchouli: 1.0-17
LLibrary: 1.7.17
Baubles: 1.5.2

### Small additional note
A small suggestion for the cauldron: have a means of emptying it out without needing to break and replace it. I thought that perhaps shift-right-clicking it might work, much like Thaumcraft crucibles, but I suppose that that's already used to change the position of the handle. Maybe some sort of simple ingredient can be put it in the cauldron to empty it completely, like wood ash?

**Comment by DaveArndt** [comment]
This looks pretty easy to fix, but I don't know what the intended behavior is. We need to get the head devs' input on this. The relevant code is here:
https://github.com/Um-Mitternacht/Bewitchment/blob/2468bbd9d8b68a02f17806172315c3b40681e938/src/main/java/com/bewitchment/common/content/cauldron/behaviours/CauldronBehaviourBrewing.java#L53-L60

The cauldron holds 1000 mB, and drinkable brews bottle 300 at a time. Either all brew volumes should be factors of 1000, or you should be able to empty the cauldron or otherwise deal with having a non-usable amount of fluid remaining.

**Comment by CammiePone** [comment]
Actually, you can empty it using wood ash. Toss that in, and it'll empty it completely. Also, thank you, Dave. You found what I was unable to find.

**Comment by CammiePone** [comment]
Also, it's confirmed that this is intended behaviour
