### ISSUE TITLE
Illegal Access crash- possible class change at runtime

### ISSUE THREAD

**Issue by iccarusA** [Um-Mitternacht/Bewitchment#268]
### Actual Behavior
I can't open the server with this mod

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
last last last

### Logs, in the event of a crash
https://paste.dimdev.org/uzuhiregac.sql

**Comment by Sunconure11** [comment]
bruh

**Comment by DaveArndt** [comment]
@Sunconure11 Why is a new EntityAITaskEntry being instantiated from living.tasks instead of importing net.minecraft.entity.ai.EntityAITasks?

https://github.com/Um-Mitternacht/Bewitchment/blob/bc8a773fac2e98a1640ae0fa1c5e14e8d65e26a3/src/main/java/com/bewitchment/common/content/transformation/vampire/VampireAbilityHandler.java#L297
