### ISSUE TITLE
Game crash upon attempting to load

### ISSUE THREAD

**Issue by Ayrion** [Um-Mitternacht/Bewitchment#331]
### Expected Behavior
Game to load

### Actual Behavior
Game crashes

### Steps to Reproduce
Load game

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12.2, 1.12.2-0.0.20.1_rewrite. 14.23.5.2825, 1.0-18. 1.7.18-1.12.2. 1.12-1.5.2

### Logs, in the event of a crash
[crash-2019-04-07_09.34.24-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/3051357/crash-2019-04-07_09.34.24-client.txt)

**Comment by Sunconure11** [comment]
What the flopping fish

**Comment by RuneKeeper666** [comment]
Expected Behavior
Game to load

Actual Behavior
Game crashes

Steps to Reproduce
Load game

Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
Bewitchment-1.12.2-0.0.19.46-indev.jar.,  1.12.2-forge1.12.2-14.23.5.2775, Patchouli-1.0-16.jar, llibrary-1.7.12-1.12.2.jar, Baubles-1.12-1.5.2.jar

Crash report   
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/PotionEvent$PotionApplicableEvent

**Comment by Sunconure11** [comment]
Use the latest build of Forge. This will not be a problem in the rewrite.

**Comment by RuneKeeper666** [comment]
Thanks
