### ISSUE TITLE
Black Dogs are game-breaking

### ISSUE THREAD

**Issue by Gabby2805** [Um-Mitternacht/Bewitchment#366]
The Black Dogs are really ruining my game.

They spawn in ridiculous numbers, every night is a total apocalypse. I cannot step foot outside at night without being swarmed by about 10 dogs at a time. They are also totally destroying my villages, killing villagers every night.

They are also invisible MOST of the time when fighting them. Whilst I get what you're going for with the brief periods of invisibility to make them seem ghostly, its just coming across as buggy and broken at the moment.

They are also still attacking through walls and have a ridiculous hitbox. I have seen that this issue had been posted but was closed and said that it had been fixed...the issue is definitely not fixed in the latest version on CurseForge.

I'm heavily relying on this mod to replace Witchery, it used to be my favourite mod, so I really appreciate the development and hard work going into this. But please, fix existing problems before adding more and more unpolished features.

P.S. Please consider bringing back glintweed from Witchery, it was a beautiful, natural, and magical way of lighting up an area and I'm really missing it.

Thank you, keep up the great work.

**Comment by MoriyaShiine** [comment]
The reason things have been marked as closed is because they have been fixed in the rewrite, in which I completely remade the mod from scratch; we've actually been focusing on removing some unpolished features, and refining the ones remaining. As for the black dogs, their spawn rate has been significantly reduced, and their attack damage and hitboxes haved been adjusted, and are no longer op as hell. Their eyes will also glow when invisible, so they aren't obnoxious, but I'm not sure if this is in the current build on CurseForge. The rewrite is nearing release, so these will be fixed sooner or later, we have one major bug to fix and that's all that's left.

**Comment by Gabby2805** [comment]
That sounds fantastic - amazing work! I'm really looking forward to the release then. Where is best to look out for the release? Does it take a while to be released on CurseForge?

**Comment by MoriyaShiine** [comment]
The best place is probably the discord (https://discord.gg/us59EkM), there will be a ping to everyone when it's out. The CurseForge file usually gets uploaded within a couple hours, so the time between the rewrite being done and it being released shouldn't be long.

**Comment by MokahTGS** [comment]
I'm curious if black dogs are going to be seen as hostile mobs in the rewrite?  Right now, the MC AI doesn't seem to categorize them the same way as zombies so Iron Golems are ignoring them.
