### ISSUE TITLE
Patch the mantle properly

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#38]
Mantle is derpy and needs fixing

**Comment by Ingoleth** [comment]
Things to fix/add: 

- [ ] Hood's rotation; atm it follows the players head until the body rotates (since that rotates the whole model, thus moving the hood out of phase

- [ ] Whilst capeFrontRight/Left already rotates out of the way when you run, they should also do so when you are holding an item in the respective hand;

- [ ] armRight/Left should rotate with the arm. (Do note that there might be some weirdness with the rotations of these two. Poke me if you see weird stuff happen)

- [ ] Add a floaty animation (slight back an forth x rotation, increases with LimbSwingAmount)

- [ ] Maybe the scale of the mantle can change depending on whether or not you are wearing armour?

**Comment by Sunconure11** [comment]
Is this still needed?
