### ISSUE TITLE
[Rewrite - 0.0.20.3] Additional Thaumcraft Compatibility

### ISSUE THREAD

**Issue by TechnoMysterio** [Um-Mitternacht/Bewitchment#386]
When playing through the rewrite, I noticed that a lot of the helpful Thaumcraft compatibility stuff from earlier Bewitchment versions seems to have been purged. I'm sure there's a good reason for this, but it would be good to reimplement some of the simpler TC comatibility stuff:

- Everfull Urn remotely filling Witches' Cauldrons. This was very handy, and the Urn does automatically fill other water containers like Botania's Petal Apothecary and ordinary Cauldrons, so this would be useful to reimplement. It might also be worth implementing something akin to old Witchery's Brew of Endless water for modpacks that focus only on Bewitchment
- Nitor for boiling Witches' Cauldrons. This would be useful for wooden huts, certainly, although it might also be worth having a Bewitchment-specific means of safely boiling Cauldrons, perhaps another bottled fire similar to the old _/chant ignis_ flame pre-rewrite.
- Infusion Stabilising Bewitchment Items. This one isn't as important, and it was rather buggy pre-rewrite with BW items giving Infusions way too much stability, but perhaps one or two simple items that add a little bonus stability might be good.

## Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
BW: 0.0.20.3
Forge: 14.23.5.2838
Baubles: 1.5.2
Patchouli: 1.0-20

**Comment by TechnoMysterio** [comment]
After some more experimentation with the mod, another possible thing to add Thaumcraft compatibility for would be the Bellows. The Bellows aren't only used for the Infernal Furance in TC, they can also speed up ordinary furnace cooking and make Crucibles boil faster. As such, it might be good to allow Bellows to speed up cooking in the Witches Oven and allow the Witches Cauldon to be brought to the boil faster too.

**Comment by Gabby2805** [comment]
I'd really like nitor to be recognised as a heat source by the cauldron. I really appreciate the compatibility there is for Thaumcraft, Bewitchment ingredients are really useful for Thaumcraft too. However, while it might seem like a very small thing, it would make a huge difference to me if I could safely boil the cauldron using nitor because I like it to be out in the open and it would nicely match my Thaumcraft crucible. It's really annoying having to surround the cauldron in stone blocks and light a netherrack every time I want to use it. The latest update is fantastic and I really hope this little feature can be added to the next update.

**Comment by Sunconure11** [comment]
All but urns refilling cauldrons are present.
