### ISSUE TITLE
Client Crash using Tipped Arrows

### ISSUE THREAD

**Issue by JoelZBub** [Um-Mitternacht/Bewitchment#442]
### Expected Behavior
Shooting mobs with tipped arrows would cause them harm.

### Actual Behavior
Shooting mobs with tipped arrows causes the game client harm instead. (It crashes)
Error is 
`java.lang.ClassCastException: com.bewitchment.common.entity.misc.ModEntityTippedArrow cannot be cast to net.minecraft.entity.EntityLivingBase`

### Steps to Reproduce
This particular crash happens when shooting at a Cannibalism Turned Villager. 

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2
0.0.20.8
14.23.5.2838
1.0-20
1.5.2
Cannibalism version: 5.6.1

### Logs, in the event of a crash
https://pastebin.com/bDq4spqG

**Comment by nextekoz** [comment]
[crash-2019-10-12_03.26.13-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/3719185/crash-2019-10-12_03.26.13-client.txt)
Shooting at a mob using a vanilla enchanted bow.

Req: Could the PotionEffect effect on arrows be set as a config option

**Comment by anqingchen** [comment]
i *think* that's a cannibalism issue, though we have made some changes on our side with tipped arrows so that could have been resolved? please test.

Also, what did you mean "Could the PotionEffect effect on arrows be set as a config option", did you want a config option to disable crafting tipped arrows with BW effects?

**Comment by anqingchen** [comment]
closing, no response
