### ISSUE TITLE
On a server after flying with any broom you are unable to dismount

### ISSUE THREAD

**Issue by AkiKuneko** [Um-Mitternacht/Bewitchment#455]
### Expected Behavior
hit LSHIFT and you get off

### Actual Behavior
after flying for a random amount of time you will become stuck on the broom.

### Steps to Reproduce
use any broom
fly around on a server loading more chunks 
then attempt to dismount

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
bewitchment-1.12.2-0.0.21.0
forge-1.12.2-14.23.5.2847
patchouli 1.0-2.0
baubles 1.5.2

### Screenshots encouraged

![2019-11-30_06 05 59](https://user-images.githubusercontent.com/58326982/69900351-93adee80-1337-11ea-876f-0b42fbc59d75.png)
![2019-11-30_06 06 00](https://user-images.githubusercontent.com/58326982/69900352-94468500-1337-11ea-87d9-ff1230d0877d.png)

**Comment by Sunconure11** [comment]
Can someone test and confirm this issue? Because if it is... JFC, we will go through broom hell again

**Comment by XyCrosier** [comment]
Using the same versions of forge, patchouli, and baubles as OP. Using latest version of Bewitchment (1.12.2-0.0.21.2)

Other mods present.

I just experienced the same issue in my single player world. It was a freshly created juniper broom. After reloading the world, I have not had any further issues with that broom (Even after breaking and replacing).

I've made two more brooms (elder) since then, and each one has had the same problem. I tried fixing the first one by using a boat to force a dismount, which worked, but resulted in the loss of the broom (it vanished without any trace.) Reloading while riding the second broom seems to have fixed that one so far.

Ultimately, every broom I've used so far has only experienced this bug on its first use.
Admittedly, this is a very small sample size, but I'm only reporting my experiences as encountered in a regular survival play-through; not testing/creative.

Hopefully this information is helpful.

**Comment by Jiroga** [comment]
Little late, but can also confirm.

Bewitchment Version: 1.12.2-0.0.21.0
Forge Version: 1.12.2-14.23.5.2847
Other mods are present, including Pautchouli and Baubles.

Flying around in the broom in pre-loaded chunks works wonderfully, however when flying through un-loaded chunks or generating new chunks with the broom the player is unable to dismount and becomes unhittable (tried to get myself killed through mobs to dismount, was unable to even get hit).

Pretty much all the previous accounts were also experienced: happened with all 4 brooms (both made by survival means and obtained through creative inventory), and finding other unorthodox ways to dismount (such as vanilla boats or mod chairs) resulted in a lost broom; all this was attempted in both singleplayer and server worlds. Logging out of the world and back in dismounted the player yet still causes issues when loading unloaded/new chunks.

Edit:

Updated to 1.12.2-0.0.21.3.jar with the same environment, I'm still experiencing the same issues through a server world. Haven't tested in singleplayer yet. Best of luck squashing bugs!

**Comment by anqingchen** [comment]
Known issue, please update to the newest version. Should be a little better. In testing, most of the time player can safely dismount

**Comment by XyCrosier** [comment]
I'm still playing single-player using the latest release version of Bewitchment (1.12.2-0.0.21.2)

Update:
Over the last 10 days, I've experience this issue a handful of times. Exiting to the main menu has enabled me to dismount every time. Just recently, one of my brooms mysteriously vanished (dismounted, went inside a structure, made a villager trade, came back out and it was gone.) This prompted me to adopt the habit of 'breaking' my broom down to item form whenever I dismount.

Since I've started breaking my broom, I've been experiencing this issue frequently. Ordinarily, I'd simply leave it in entity form, only packing it for convenience on the rare occasion. There appears to be some connection between the initial in-world placement of a broom and the occurrence of this bug.

For me, this issue appears to have nothing to do with whether or not the chunks I visit have been previously generated; I filled a very large vanilla map region via exploration quite some time ago, and I have only been playing and experiencing this bug within those confines. However, this issue does appear to be tied to distance or whether or not the chunks were already loaded into RAM. I say this because I have not experienced this issue over very short distances with any broom.

Summary:
If I had to speculate, I'd say the client and server are in disagreement about something concerning freshly spawned brooms and the state of players riding those brooms over some distance.

@anqingchen , when you say "update to the newest version" were you referring to the latest release (1.12.2-0.0.21.2) or a newer test build?

**Comment by anqingchen** [comment]
I think there's a version 1.12.2-0.0.21.3 out with a little better dismounting stuff. Just because of minecraft limitations on entities carrying another entity, I'm trying my best to sync it up but it still messes up occasionally.

**Comment by mxnmnm** [comment]
still an issue on 0.0.21.11 ;-;

**Comment by Sunconure11** [comment]
Broom fixes on 1.12 were attempted many times. None were successful. None of the devs have been able to figure this one out fully, it’s eluded even the best.
