### ISSUE TITLE
How do I get the ghosts to stay away?

### ISSUE THREAD

**Issue by bafomdad** [Um-Mitternacht/Bewitchment#463]
ignoring template, since this is a question

I'm minding my own business, reading books here and there, flipping through pages and pages of items and blocks in JEI trying to figure out what aesthetic blocks to use for building with, and these fucking ghosts just zooms on through solid blocks (because of course they can, they're ghosts) and bumps into me. repeatedly. and at that point, the damage they do are superficial (but my armor durability...!) and yet all I can think of when I whip out my bitch sticker and escort them to the real afterlife is this video:
https://www.youtube.com/watch?v=Cr-wOQSUWQk

oh, right. question is in the title :]

**Comment by Sunconure11** [comment]
We're aware of this issue, but no solution has managed to come to light fully due to their ability to phase through even things like salt barriers, which act as a fence to undead and other abominations.

**Comment by IdrisQe** [comment]
I can think of a few solutions, based on what it sounds like the issue is, anyway.

1. Make it so they can't see the player through blocks unless the player is already targeted by them, but can still move through them. This will stop them from randomly attacking you when you're in a safe place. In addition, perhaps make it so they won't path through blocks unless they're currently targeting a player so they won't accidentally wander into sight of a player.

2. Make a placeable item (there are TONS of things like these in folklore) which wards off spirits, causing ghosts to stay away in a similar way to how Cats make Creepers run away.

3. Make them be unable to cross salt, period. Have their pathing actively avoid the entire Y axis where salt is placed. Would this be OP in making ghost traps? Yeah probably, but it also makes sense.

**Comment by Sunconure11** [comment]
Salt is basically our number 2, but due to how ghosts currently work, 3 is currently not functional.

**Comment by Sunconure11** [comment]
There was an idea proposed to fix them. I’ll look into it if I’m bored enough.
