### ISSUE TITLE
Tarrots Missing in new Book of Shadows Design

### ISSUE THREAD

**Issue by PresquePlayed** [Um-Mitternacht/Bewitchment#477]
I guess the title says it all, I cant fid the chapter on taraots...

**Comment by MaskedElephant** [comment]
Although a little late, I can confirm, additionally, the book also doesn't show how to make the divination table or tarot cards.

**Comment by Roseplate** [comment]
I can ALSO verify that they are not there for I have been searching for upwards of 2 hours because there's this card and I don't know what it means I think it might be the sword but I'm not sure. and I'm sorta spooked by it (its got steve in a witch or pilgrims hat with a pickaxe as well as a sword with a witch and some sort of dog demon in the background)

**Comment by Sunconure11** [comment]
Tarots have since been pulled, and will reappear in an addon on 1.16.* or later.
