### ISSUE TITLE
Unable to create stew of the grotesque

### ISSUE THREAD

**Issue by melodious1963** [Um-Mitternacht/Bewitchment#559]
### Expected Behavior
Receiving the stew of the grotesque after dropping in the last ingredient.

### Actual Behavior
Not receiving the stew of the grotesque

### Steps to Reproduce
Attempt to create the stew of the grotesque

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Bewitchment: 1.12.2-0.0.21.11
Forge: 14.23.5.2847
Patchouli: 1.0-20
Baubles: 1.12-1.5.2

**Comment by Sunconure11** [comment]
You need altar power to make this. Please provide pictures of your current altar set up.

**Comment by melodious1963** [comment]
I currently have two altars (I don't remember why exactly), the first one has 2452 altar power and the second one has 1331 altar power.
https://i.imgur.com/3Ao5H19.png
https://i.imgur.com/bfU2JiL.png
https://i.imgur.com/gJKgmT7.jpg

**Comment by Sunconure11** [comment]
Is your cauldron filled with water? It needs to be filled with water in the first place.

Also, you only need one altar for this.

**Comment by melodious1963** [comment]
....
Of course my cauldron is filled with water, it wouldn't even accept the items in the first place, would it?
I know I only need one altar, as I said, I don't remember why I had the second one in the first place.
For now, I moved the second altar as I needed it for automatic brewing :)

**Comment by melodious1963** [comment]
Any progress regarding this issue by any chance?

**Comment by Sunconure11** [comment]
No, but I may have found something. Try putting the items in without using the keybind for dropping items. Drag them out of your inventory and put them in.

**Comment by melodious1963** [comment]
I tried that with the latest build, didn't work unfortunately...

**Comment by melodious1963** [comment]
Out of curiosity, how much altar power is needed to create the stew of the grotesque?

**Comment by SmallEnderman** [comment]
let's just say u need atleast 2k. i think i might see an issue, here are some things to fix it
1. remove the lowest AP (altar power) Altar, it might be that the cauldron checks for the lowest one first and then says naah u dont have enough mate. (this is due to the 2 altars being wayyyy to close to each other, best to just remove one)
2. if ya think you dont have enough AP, upgrade it a bit more, add a wither skeleton skull/dragon head (dragon head > Wither skull) and use end rod, filled chalice and a blade (the stronger the better but not all blades work, for now use diamond) this should increase the altar's regenration rate aswell as increased power. also note that The more plants added... the better
3. Consider this post is made in april 23, try to update to the latest version, perhaps it WAS a bug and was fixed/patched while we didnt notice it.
4. Do you have performant installed? if so, dont. Performant is a nice performence mod not gonna lie but it messes with the cauldron. What it does is basically make the cauldron think u dropped in 2 items instead of ur original 1 item drop. If you have performant installed either temporarely disable it or remove the mod

if none of these things help, then i do not know what causes this and will do further investigations for you

Sincerely

SmallEnderman
