### ISSUE TITLE
Brew not working.

### ISSUE THREAD

**Issue by crotin1111** [Um-Mitternacht/Bewitchment#565]
### Expected Behavior
Ability to pick up liquid with glass bottle or the other bottle from thaumcraft after brewing ingredients

### Actual Behavior
well not able to pick it up

### Steps to Reproduce
1. brew.
add the first ingredient to make a potion
add an apple. 
use a bottle

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2 and the rest is all in the hastebin link below
https://paste.dimdev.org/agamibenuy.md

### Screenshots encouraged
I have none as my computer acts way to slow for that

### Logs, in the event of a crash
None unfortunately

**Comment by ubergarm** [comment]
Side note for anyone else that comes across any of these issues (#605) (#475) trying to figure out the Bewitchment Cauldron Brews:

1. Make sure you have built an altar and it shows at least a couple hundred power when you right click it.
2. Place your *bewitchment* cauldron over a heat source e.g. lava or burning Netherrack etc closer than 16 blocks from altar
3. Fill cauldron with water from a bucket and wait for it to boil.
4. Toss in a piece of mandrake using `q` and it will splash into the boiling cauldron.
5. If the water turns Light Blue, you're good to continue whatever recipe you want.
6. Finish up the recipe and right click the cauldron with empty vanilla glass bottles (fills exactly 3).

If the water turns [Reddish Brown](https://www.color-hex.com/color/604040) after tossing in the mandrake, then *STOP* because you'll waste the rest of your ingredients, and will be unable to scoop any of this invalid liquid out with your glass bottles. You can break the cauldron or more typically throw some wood ash to clear it.

In my experience testing on `bewitchment-1.12.2-0.0.22.37.jar`, these are the reasons it might not be letting you brew:
1. You didn't build an altar with some available power close enough to your cauldron
2. Your modpack may contain [Performant](https://www.curseforge.com/minecraft/mc-mods/performant) which seems to be incompatible.
3. You are using server software other than forge, e.g. I personally confirmed brewing does not work with `Mohist-1.12.2-b71b544-server.jar`, but worked fine as soon as I switched back to `forge-1.12.2-14.23.5.2854.jar`, gonna open a bug ticket over with the Mohist folks.

Okay, happy brewing everyone!

EDIT: [Cross Reference to Mohist Github Issues](https://github.com/Mohist-Community/Mohist/issues/544)

**Comment by Sunconure11** [comment]
I was considering using mohist for a server. Do keep me informed on how it goes @ubergarm.

**Comment by ubergarm** [comment]
@Sunconure11 I just finished my [Sky Magic Islands](https://www.curseforge.com/minecraft/modpacks/sky-magic-islands/screenshots) modpack. I have both the client and server (with latest Mohist 1.12.2) and it runs pretty well with almost ~150 mods (including Bewitchment of Course!).

I didn't re-test this specific cauldron issue yet, but they haven't touched the open ticket yet (seems like they're moving towards 1.16 maybe)

Anyway, cheers!
