### ISSUE TITLE
Witches Oven Bug creating terra-cotta from nothing

### ISSUE THREAD

**Issue by lunarmaximum** [Um-Mitternacht/Bewitchment#581]
I created a witches oven and placed it down and added coal and it immediately started cooking with nothing and started terra-cotta out of thin air

Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
bewitchment-1.12.2-0.0.21.12
forge-1.12.2-14.23.5.2847

Mods I have downloaded in my server:
Abyssal Craft
Damage Indicator
Aether Legacy
Ancient Warfare 2
Animania
Advent of Ascension
AppleCore
Electroblob Wizardry
Arcane Essentials (EB)
Seeds for Wizardry (EB)
TF Spell Pack (EB)
Better FPS
Bibliocraft
BiomesOPlenty-1.12.2-7.0.1.2444-universal
Botania
CarryOn
CodeChickenLib-1.12.2-3.2.3.358-universal
comforts-1.12.2-1.4.1.2
CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
CTM-MC1.12.2-1.0.2.31
davincisvessels-1.12-6.340-full
EnchantmentDescriptions-1.12.2-1.1.15
Fairy Lights
Fast Leaf Decay
foamfix-0.10.10-1.12.2
Forgelin-1.8.3
Mr Crayfish Furniture Mod
GalacticraftCore
GalacticraftPlanets
Hunger Overhaul
Ice and Fire Dragons
Inventory Tweaks
Just enough items (necessary for NEI)
librarianlib-1.12.2-4.20-release
llibrary-1.7.19-1.12.2
lycanitesmobs-1.12.2-2.0.7.1
MicdoodleCore-1.12.2-4.0.2.272 (Galacticraft)
More-Planets-1.12.2-2.0.24-GC251 (Galacticraft)
movingworld-1.12-6.342-full
NotEnoughItems-1.12.2-2.4.3.245-universal
Pam's Harvest Craft
Phosphor
Serene Seasons
SimpleStorageNetwork-1.12.2-1.7.10
The Midnight
Corail's Tombstone
Tumbleweed
Twilight Forest
Vanilla Fix
Wings

**Comment by DarianLStephens** [comment]
Interesting.
I'm having a similar bug, only my cauldron is miraculously producing Charcoal, which makes it an infinite, potentially self-sustaining power source.
In fact with a setup as simple as this, it produces enough charcoal to completely fill itself. It unfortunately then goes in to the top slot, and apparently only the vanilla hopper can interact with it, so the process is halted once its fuel slot is filled, but I just haven't bothered working out a way to fix that yet because it just works.
![2020-05-31_04 48 57](https://user-images.githubusercontent.com/15375876/83336856-34d32d00-a2fa-11ea-991b-46114ba88b1f.png)
![2020-05-31_04 50 44](https://user-images.githubusercontent.com/15375876/83336872-52a09200-a2fa-11ea-8f99-95aceb1ce20b.png)
![2020-05-31_04 50 47](https://user-images.githubusercontent.com/15375876/83336881-56341900-a2fa-11ea-9be3-01777ba9fb31.png)

**Comment by Sunconure11** [comment]
Known issue, but no fix has come to light. Please direct someone here if you think they can fix it.
