### ISSUE TITLE
[Crash] Attempt to access a package private member if VanillaFix is installed

### ISSUE THREAD

**Issue by T-Dark0** [Um-Mitternacht/Bewitchment#657]
### Expected Behavior
VanillaFix's presence or absence should presumably not cause the game to fail launching

### Actual Behavior
VanillaFix's "your game crashed" screen pops up (See screnshoot 1)

### Steps to Reproduce
1: Install multiMC
2: Create a vanilla 1.12.2 instance
3: Add forge
4: Put Bewitchment and dependencies in the mods folder
5: Put VanillaFix there as well
6: Launch the game, and it will crash

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Bewitchment: 1.12.2-0.0.22.40 (also tried with 1.12.2-0.0.22.39)
Forge: 14.23.5.2854
Patchouli: 1.0-21
Baubles: 1.12-1.5.2

VanillaFix: 1.0.10-99

### Screenshots encouraged
![VanillaFix crash screen](https://user-images.githubusercontent.com/60000771/94468092-cde85680-01bb-11eb-9156-ecd5a7692dec.png)

### Logs, in the event of a crash
[Crash log](https://github.com/Um-Mitternacht/Bewitchment/files/5294144/crash-2020-09-28_18.47.46-client.txt)

**Comment by T-Dark0** [comment]
Update: Downgrading VanillaFix to 1.0.7-72 seems to be a functional workaround. I haven't tested the versions between 1.0.7-72 and 1.0.10-99, however.

Should I open this issue on VanillaFix's tracker as well?

**Comment by SmallEnderman** [comment]
It probably has to do with mixins... If our bewitchment mixins is outdated or VanillaFix's Mixins is outdated is something i cannot see... but that seems to be one of the issues

**Comment by stephen-netu** [comment]
Confirmed that [VanillaFix 1.0.10-150](https://www.curseforge.com/minecraft/mc-mods/vanillafix/download/2915154) corrects this issue.

Thank you, all!

**Comment by stephen-netu** [comment]
Confirmed that [VanillaFix 1.0.10-150](https://www.curseforge.com/minecraft/mc-mods/vanillafix/download/2915154) (latest) corrects this issue.  

Thank you, all!

**Comment by Kira076** [comment]
This issue is not unique to Vanilla Fix. I'm having this issue as well and downgrading Bewitchment from 0.0.22.44 to 0.0.21.10 resolved it for me. I'm in Australia and it's 4 am and my brain is mush but I can provide whatever logs or further information on what mods we're using when I wake up. But it is definitely not limited to Vanilla Fix and I read in https://github.com/SpongePowered/SpongeForge/issues/3069#issuecomment-581149982 that it is a problem with anything that uses a mixin version of 0.8 or higher conflicting with ones that use the older way of doing it

**Comment by Kira076** [comment]
Aha, I figured it out actually - For me it was updating JustEnoughIds... That let me upgrade to the latest bewitchment just fine
