### ISSUE TITLE
Thaumcraft + Bewitchment causing all attacks to deal double damage

### ISSUE THREAD

**Issue by SomeRandomPetey** [Um-Mitternacht/Bewitchment#675]
### Expected Behavior
Attacks deal standard amount of damage to mobs

### Actual Behavior
Attacks deal twice their normal amounts. Example: fists do 2 points instead of 1, iron swords do 12 points instead of 6, etc.

### Steps to Reproduce
Install Bewitchment + Thaumcraft (and all dependencies), and optionally a mod that can show mob health
Attack a mob, best seen with mobs with no armor.
Observe incorrect damage amount being dealt.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2, Bewitchment 0.0.22.46, Forge 14.23.5.2854, Patchouli 1.0-22, Baubles 1.5.2, Thaumcraft 6.1.BETA26

### Logs, in the event of a crash
[Video demonstration](https://www.youtube.com/watch?v=QpEMLCH7z2k)
Note: Damage indicator mod used is ToroHUD, mod does not affect results

**Comment by HamaIndustries** [comment]
Can reproduce and confirm

**Comment by Chubzik1** [comment]
Same issue, but i have a lot more mods installed. Problem appears after version 0.0.22.40 i think, because with this version all works fine.

**Comment by HamaIndustries** [comment]
I tested each version and the issue is definitely introduced in 0.0.22.42, putting it between October 14 and November 2.

3b199fa appears to be the only commit in that time frame that modifies combat which involves (silver and cold iron) weakness, particularly the thaumcraft compat weakness handling for golems. I suspect that it may be targeting all entities rather than just the golems.

edit: It also looks like beyond whatever weakness damage is applied, ThaumcraftCompat.java also doubles it with `event.setAmount(event.getAmount() * weakness * 2)`. Assuming all entities are being counted as these golems, the weakness will be 0 but the damage will still be double, despite bewitchment weakness not normally being 2x

**Comment by Sunconure11** [comment]
Check out the latest build, and see if it has been fixed.

**Comment by Chubzik1** [comment]
Fixed for me, thanks a lot!
