### ISSUE TITLE
Witches lantern render is a bit iffy

### ISSUE THREAD

**Issue by Ingoleth** [Um-Mitternacht/Bewitchment#70]
### Expected Behavior
Lantern should raise the hand that holds it; The opposing hand is raised instead...

Cause is unclear, as sometimes it works, and other times it doesn't. Might be because of other mods interference, since I'm on a modded instance. Will test on dev environment latter

https://cdn.discordapp.com/attachments/390215771965489183/506558181850480640/unknown.png

**Comment by MoriyaShiine** [comment]
this appears to already be fixed

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/52907949-ef403d00-3239-11e9-9cab-6b0a47a1e3a5.png)
Yep, still around.

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/52907960-1bf45480-323a-11e9-8fee-f952f96d43d6.png)
Fixed itself afer dropping it :/

**Comment by DaveArndt** [comment]
I have it so the correct hand raises, but because of the way it's been implemented this whole time, it overrides the swing animation. Now it just looks like you're breaking blocks with the power of your mind. Someone with a solid grasp of models and animation needs to look at this. You'll probably need to throw out everything that's been done so far and modify the fields of evt.getRenderer().getMainModel(). When I try, it just turns into an abomination.
